# Generated by Django 5.0 on 2026-04-14 19:59

import datetime
import django.db.models.deletion
import django.utils.timezone
import menuproject.api.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accessing_Devices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_description", models.CharField(default="", max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Buy_order_session_id",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyOrderSessionID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy_order", models.PositiveBigIntegerField(default=1)),
                ("session_id", models.PositiveBigIntegerField(default=1)),
                (
                    "transaction_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_name", models.CharField(default="", max_length=80)),
                ("private_name", models.CharField(default="", max_length=80)),
                ("public_description", models.CharField(default="", max_length=500)),
                ("private_description", models.CharField(default="", max_length=500)),
                ("public_view_order", models.IntegerField(null=True)),
                ("private_view_order", models.IntegerField(null=True)),
                ("public_image_id", models.BigIntegerField(default=-1)),
                ("private_image_id", models.BigIntegerField(default=-1)),
                ("recently_created", models.BooleanField(default=True)),
                ("has_been_modified", models.BooleanField(default=False)),
                ("marked_for_deletion", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=80)),
                ("alpha2_code", models.CharField(default="", max_length=2)),
                ("locale", models.CharField(default="", max_length=5)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("flag_image_url", models.URLField(default="", max_length=254)),
                ("currency_symbol", models.CharField(default="", max_length=6)),
                ("minimum_fraction_digits", models.IntegerField(default=0)),
                ("maximum_fraction_digits", models.IntegerField(default=0)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "No Selection"),
                            ("RUT", "Registro Único Tributario"),
                            ("CUIT", "Código Único de Identificación Tributaria"),
                            ("EIN", "Employer Identification Number"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Global_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "full_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "initial_menu_load",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Help_Atonn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_name", models.CharField(default="", max_length=80)),
                ("video_url", models.URLField(default="", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="New_Restaurant_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(default="", max_length=30, unique=True)),
                ("country_id", models.BigIntegerField(default=-1)),
                ("price_type", models.CharField(default=None, max_length=20)),
                ("user_name", models.CharField(default="", max_length=80)),
                ("user_password", models.CharField(default="", max_length=512)),
                ("user_email", models.EmailField(default="", max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Past_Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rejection_Reason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(default="", max_length=80)),
                ("explanation", models.CharField(default="", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Super_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=80)),
                (
                    "password",
                    models.CharField(
                        default="gAAAAABmkTV4y8NR-Pmy_FsBOzEecCpJOvG9akb7xQOeo04pC_MVe9TGevZ7OIs43kI4prB1CtylFtrZHp0Gplya2I9KCHQtPA==",
                        max_length=512,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery_Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=80)),
                ("company_image_url", models.URLField(default="", max_length=254)),
                ("url_template", models.CharField(default="", max_length=254)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_name", models.CharField(default="", max_length=80)),
                ("private_name", models.CharField(default="", max_length=80)),
                ("public_description", models.CharField(default="", max_length=500)),
                ("private_description", models.CharField(default="", max_length=500)),
                ("public_price", models.CharField(default="0.0", max_length=30)),
                ("private_price", models.CharField(default="0.0", max_length=30)),
                ("public_view_order", models.IntegerField(null=True)),
                ("private_view_order", models.IntegerField(null=True)),
                ("public_image_id", models.BigIntegerField(default=-1)),
                ("private_image_id", models.BigIntegerField(default=-1)),
                ("previous_dish_number_of_reviews", models.IntegerField(default=0)),
                ("previous_dish_reviews_average", models.IntegerField(default=0)),
                ("recently_created", models.BooleanField(default=True)),
                ("marked_for_deletion", models.BooleanField(default=False)),
                ("marked_for_deletion_by_parent", models.BooleanField(default=False)),
                ("has_been_modified", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment_Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=80)),
                (
                    "payment_option_image_url",
                    models.URLField(default="", max_length=254),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(default="", max_length=30, unique=True)),
                ("public_name", models.CharField(default="", max_length=80)),
                ("private_name", models.CharField(default="", max_length=80)),
                (
                    "public_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "private_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("public_address", models.CharField(default="", max_length=250)),
                ("private_address", models.CharField(default="", max_length=250)),
                ("public_phone", models.CharField(default="", max_length=25)),
                ("private_phone", models.CharField(default="", max_length=25)),
                ("public_facade_image_id", models.BigIntegerField(default=-1)),
                ("private_facade_image_id", models.BigIntegerField(default=-1)),
                ("public_logo_image_id", models.BigIntegerField(default=-1)),
                ("private_logo_image_id", models.BigIntegerField(default=-1)),
                ("public_show_images", models.BooleanField(default=True)),
                ("private_show_images", models.BooleanField(default=False)),
                ("public_show_restaurant_reviews", models.BooleanField(default=True)),
                ("private_show_restaurant_reviews", models.BooleanField(default=True)),
                ("public_show_dishes_reviews", models.BooleanField(default=True)),
                ("private_show_dishes_reviews", models.BooleanField(default=True)),
                ("public_show_prices", models.BooleanField(default=True)),
                ("private_show_prices", models.BooleanField(default=True)),
                ("public_show_ask_button", models.BooleanField(default=True)),
                ("private_show_ask_button", models.BooleanField(default=True)),
                (
                    "public_instagram_url",
                    models.URLField(blank=True, default="", max_length=80),
                ),
                (
                    "private_instagram_url",
                    models.URLField(blank=True, default="", max_length=80),
                ),
                (
                    "public_facebook_url",
                    models.URLField(blank=True, default="", max_length=80),
                ),
                (
                    "private_facebook_url",
                    models.URLField(blank=True, default="", max_length=80),
                ),
                (
                    "public_twitter_url",
                    models.URLField(blank=True, default="", max_length=80),
                ),
                (
                    "private_twitter_url",
                    models.URLField(blank=True, default="", max_length=80),
                ),
                (
                    "public_website_url",
                    models.URLField(blank=True, default="", max_length=254),
                ),
                (
                    "private_website_url",
                    models.URLField(blank=True, default="", max_length=254),
                ),
                (
                    "public_monday_open_hour_in_minutes",
                    models.IntegerField(default=660),
                ),
                (
                    "public_tuesday_open_hour_in_minutes",
                    models.IntegerField(default=660),
                ),
                (
                    "public_wednesday_open_hour_in_minutes",
                    models.IntegerField(default=660),
                ),
                (
                    "public_thursday_open_hour_in_minutes",
                    models.IntegerField(default=660),
                ),
                (
                    "public_friday_open_hour_in_minutes",
                    models.IntegerField(default=660),
                ),
                (
                    "public_saturday_open_hour_in_minutes",
                    models.IntegerField(blank=True, default=660),
                ),
                (
                    "public_sunday_open_hour_in_minutes",
                    models.IntegerField(blank=True, default=660),
                ),
                ("private_monday_open_hour_in_minutes", models.IntegerField(default=0)),
                (
                    "private_tuesday_open_hour_in_minutes",
                    models.IntegerField(default=0),
                ),
                (
                    "private_wednesday_open_hour_in_minutes",
                    models.IntegerField(default=0),
                ),
                (
                    "private_thursday_open_hour_in_minutes",
                    models.IntegerField(default=0),
                ),
                ("private_friday_open_hour_in_minutes", models.IntegerField(default=0)),
                (
                    "private_saturday_open_hour_in_minutes",
                    models.IntegerField(default=0),
                ),
                ("private_sunday_open_hour_in_minutes", models.IntegerField(default=0)),
                (
                    "public_monday_close_hour_in_minutes",
                    models.IntegerField(default=-210),
                ),
                (
                    "public_tuesday_close_hour_in_minutes",
                    models.IntegerField(default=-210),
                ),
                (
                    "public_wednesday_close_hour_in_minutes",
                    models.IntegerField(default=-210),
                ),
                (
                    "public_thursday_close_hour_in_minutes",
                    models.IntegerField(default=-210),
                ),
                (
                    "public_friday_close_hour_in_minutes",
                    models.IntegerField(default=-210),
                ),
                (
                    "public_saturday_close_hour_in_minutes",
                    models.IntegerField(default=-210),
                ),
                (
                    "public_sunday_close_hour_in_minutes",
                    models.IntegerField(default=-210),
                ),
                (
                    "private_monday_close_hour_in_minutes",
                    models.IntegerField(default=-120),
                ),
                (
                    "private_tuesday_close_hour_in_minutes",
                    models.IntegerField(default=-120),
                ),
                (
                    "private_wednesday_close_hour_in_minutes",
                    models.IntegerField(default=-120),
                ),
                (
                    "private_thursday_close_hour_in_minutes",
                    models.IntegerField(default=-120),
                ),
                (
                    "private_friday_close_hour_in_minutes",
                    models.IntegerField(default=-120),
                ),
                (
                    "private_saturday_close_hour_in_minutes",
                    models.IntegerField(default=-120),
                ),
                (
                    "private_sunday_close_hour_in_minutes",
                    models.IntegerField(default=-120),
                ),
                ("restaurant_creation_date", models.DateField(auto_now_add=True)),
                ("restaurant_recently_created", models.BooleanField(default=True)),
                (
                    "restaurant_current_date",
                    models.DateField(default=menuproject.api.models.get_yesterday),
                ),
                (
                    "restaurant_current_day",
                    models.IntegerField(default=menuproject.api.models.get_current_day),
                ),
                (
                    "restaurant_current_month",
                    models.IntegerField(
                        default=menuproject.api.models.get_current_month
                    ),
                ),
                ("main_user_id", models.IntegerField(default=-1)),
                (
                    "previous_restaurant_number_of_reviews",
                    models.IntegerField(default=0),
                ),
                ("previous_restaurant_reviews_average", models.IntegerField(default=0)),
                ("update_image_uses", models.BooleanField(default=False)),
                ("todays_random_number", models.IntegerField(default=-1)),
                ("currently_logged_in", models.IntegerField(default=-1)),
                ("logged_in_time", models.CharField(default="", max_length=20)),
                ("logged_out_time", models.CharField(default="", max_length=20)),
                ("logged_in_user_random_number", models.IntegerField(default=-1)),
                ("menu_edition_is_pending", models.BooleanField(default=False)),
                ("reviews_updates_are_pending", models.BooleanField(default=False)),
                ("menu_sorting_is_pending", models.BooleanField(default=False)),
                (
                    "restaurant_deliveries_edition_is_pending",
                    models.BooleanField(default=False),
                ),
                ("promotions_edition_is_pending", models.BooleanField(default=False)),
                ("preferences_edition_is_pending", models.BooleanField(default=False)),
                ("users_edition_is_pending", models.BooleanField(default=False)),
                (
                    "dont_allow_further_actions_from_this_user",
                    models.BooleanField(default=False),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            (None, "No Selection"),
                            ("Full Price", "Full Price"),
                            ("Minimum Price", "Minimum Price"),
                        ],
                        default="Full Price",
                        max_length=20,
                    ),
                ),
                (
                    "next_price_type",
                    models.CharField(
                        choices=[
                            (None, "No Selection"),
                            ("Full Price", "Full Price"),
                            ("Minimum Price", "Minimum Price"),
                        ],
                        default="Full Price",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("total_number_of_accesses", models.IntegerField(default=0)),
                ("number_of_pending_free_months", models.IntegerField(default=0)),
                (
                    "last_payment_date",
                    models.DateField(
                        default=menuproject.api.models.get_day_before_first_of_month
                    ),
                ),
                (
                    "payment_state",
                    models.CharField(
                        choices=[
                            (
                                "not_blocked_due_to_payment",
                                "Restaurant not blocked due to payment",
                            ),
                            (
                                "blocked_due_to_payment",
                                "Restaurant blocked due to payment",
                            ),
                        ],
                        default="not_blocked_due_to_payment",
                        max_length=50,
                    ),
                ),
                (
                    "number_of_days_served_in_current_month",
                    models.IntegerField(default=0),
                ),
                ("number_of_sent_payment_reminders", models.IntegerField(default=0)),
                ("active_month_number", models.IntegerField(default=1)),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "private_country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="private_country",
                        to="api.country",
                    ),
                ),
                (
                    "public_country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="public_country",
                        to="api.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReactivatedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reactivation_date", models.DateField(default=datetime.date.today)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.restaurant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_name", models.CharField(default="", max_length=80)),
                (
                    "private_name",
                    models.CharField(default="Nueva Promoción", max_length=80),
                ),
                (
                    "public_attractor_text",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "private_attractor_text",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("public_promotion_text", models.TextField(default="")),
                ("private_promotion_text", models.TextField(default="")),
                ("recently_created", models.BooleanField(default=False)),
                ("has_been_modified", models.BooleanField(default=False)),
                ("marked_for_deletion", models.BooleanField(default=False)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.restaurant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Monthly_Accesses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(default="")),
                ("accesses", models.IntegerField(default=0)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.restaurant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(default="", max_length=80)),
                ("image_original_name", models.CharField(default="", max_length=80)),
                ("image_public_id", models.CharField(default="", max_length=100)),
                ("image_resource_type", models.CharField(default="", max_length=100)),
                ("image_url", models.URLField(default="", max_length=254)),
                ("use_count", models.IntegerField(default=0)),
                ("finished_setting", models.BooleanField(default=False)),
                ("image_creation_date", models.DateField(auto_now_add=True)),
                (
                    "image_next_revision_date",
                    models.DateField(
                        default=menuproject.api.models.get_next_revision_date
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.restaurant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CuttingServiceDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cutting_service_date", models.DateField(default=datetime.date.today)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.restaurant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.restaurant"
            ),
        ),
        migrations.CreateModel(
            name="Restaurant_Delivery_Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_token", models.CharField(default="", max_length=100)),
                ("private_token", models.CharField(default="", max_length=100)),
                ("recently_created", models.BooleanField(default=True)),
                ("marked_for_deletion", models.BooleanField(default=False)),
                ("has_been_modified", models.BooleanField(default=False)),
                (
                    "delivery_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.delivery_company",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.restaurant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_name", models.CharField(default="", max_length=80)),
                ("private_name", models.CharField(default="", max_length=80)),
                ("public_image_id", models.BigIntegerField(default=-1)),
                ("private_image_id", models.BigIntegerField(default=-1)),
                ("public_password", models.CharField(default="", max_length=512)),
                ("private_password", models.CharField(default="", max_length=512)),
                ("public_email", models.EmailField(default="", max_length=254)),
                ("private_email", models.EmailField(default="", max_length=254)),
                ("public_email_validated", models.BooleanField(default=False)),
                ("private_email_validated", models.BooleanField(default=False)),
                ("logged_in", models.BooleanField(default=False)),
                ("last_logged_in", models.CharField(default="", max_length=20)),
                ("last_logged_out", models.CharField(default="", max_length=20)),
                ("recently_created", models.BooleanField(default=True)),
                ("marked_for_deletion", models.BooleanField(default=False)),
                ("main_user", models.BooleanField(default=False)),
                ("has_been_modified", models.BooleanField(default=False)),
                (
                    "random_number_to_validate",
                    models.CharField(default="", max_length=4),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.restaurant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diner_name", models.CharField(default="", max_length=80)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("number_of_stars", models.IntegerField(default=5)),
                ("review_comment", models.CharField(default="", max_length=500)),
                ("public_rejected", models.BooleanField(default=False)),
                ("private_rejected", models.BooleanField(default=False)),
                ("rejection_status_just_changed", models.BooleanField(default=False)),
                ("parent_type", models.CharField(default="restaurant", max_length=100)),
                ("parent_name", models.CharField(default="", max_length=80)),
                ("has_been_modified", models.BooleanField(default=False)),
                (
                    "dish",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dish",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review_Rejection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rejection_reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.rejection_reason",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejections",
                        to="api.review",
                    ),
                ),
            ],
        ),
    ]
